### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by orliesaurus**
IMHO important step for people who don't use brew so to not end up without the right formulae definitions

### CODE REVIEW

**Comment by thibaultcha** [comment]
Actually `brew upgrade` is to update the packages once the formulas are up to date (by `brew update`). What you want is `brew update`. But this is only recommended (not required, you probably didn't run `brew update` in a long time) before installing cassandra.

So:

``` shell
$ brew update # for the cassandra formula
$ brew install kong --with-cassandra
```

**Comment by orliesaurus** [comment]
yeah that's the one ! :+1: to mention it because I am sure macos people dont really brew update all the time

**Comment by thibaultcha** [comment]
If you update you're PR with what I wrote, I'll accept it :wink: :wink:

**Comment by orliesaurus** [comment]
voil ah

**Pull request merged**
